In [12]:
import numpy as np
import pandas as pd

In [87]:
corpus = [
'this is the first document',
'this document is the second document',
'and this is the third one',
'is this the first document',
]

for doc in corpus:
    print(doc)

this is the first document
this document is the second document
and this is the third one
is this the first document


# Creating a list of all the words in corpus then making the ord vector.

In [86]:
word_list=[]
for doc in corpus:
    for each_word in doc.split(' '):
       word_list.append(each_word)
print('The list of all words used in the corpus: \n','*'*120,'\n',word_list,'\n','*'*120)

## making vocabulary out of this separate words

voc=list(set(word_list))
voc
len(voc)
print('\nThe word vector: \n','*'*80,'\n',voc,'\n','*'*80)

The list of all words used in the corpus: 
 ************************************************************************************************************************ 
 ['this', 'is', 'the', 'first', 'document', 'this', 'document', 'is', 'the', 'second', 'document', 'and', 'this', 'is', 'the', 'third', 'one', 'is', 'this', 'the', 'first', 'document'] 
 ************************************************************************************************************************

The word vector: 
 ******************************************************************************** 
 ['is', 'first', 'and', 'this', 'document', 'the', 'third', 'second', 'one'] 
 ********************************************************************************


# Comparing the vectorized vocabulary from my and sklearn code

In [76]:
vector=[0,0,0,0,0,0,0,0,0]
vector_list=[]
count=0
for each_doc in corpus:
    for i in voc:
        #print(each_doc)
        for word in each_doc.split(' '):
            if i==word:
                count+=1
        #print(count)
        vector[voc.index(i)]=count
        count=0    
    vector_list.append(vector) 
    vector=[0,0,0,0,0,0,0,0,0]
print('Own implementation: \n','*'*50,'\n',np.array(vector_list))  

from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer()
vec_sklearn=vec.fit_transform(corpus).toarray()
print('\nvector from sklearn:\n', '*'*50,'\n',vec_sklearn)
vec2=CountVectorizer( analyzer='word')
print('\nfeatures by sklearn: \n','*'*50,'\n',vec.get_feature_names())
print('\nfeatures by own implementaion: \n','*'*50,'\n',voc)

Own implementation: 
 ************************************************** 
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]

vector from sklearn:
 ************************************************** 
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]

features by sklearn: 
 ************************************************** 
 ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

features by own implementaion: 
 ************************************************** 
 ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
